### ISSUE TITLE
Wiring Diagram

### ISSUE THREAD

**Issue by iosifnicolae2** [mi-schi/hiking-meter-tasmota-plug_control_esp8266#1]
Hi.

It would be awesome if you can document the wiring diagram.

Thank you!

**Comment by mi-schi** [comment]
Hi,

there are only 4 wires defined at the top of the code. 3 are necessary, TX, RX and the switch pin for the mode to the Max485.  Do you need more information?

**Comment by iosifnicolae2** [comment]
I've tried connecting them but no success..
MAX485_TX_ENABLE_PIN -> DE,RE
MAX485_RX_PIN -> RO
MAX485_TX_PIN -> DI
3.3v/VIN -> VCC
GND -> GND
![image](https://user-images.githubusercontent.com/7108834/189708455-5c4d1371-f9a0-492b-b267-344f457345b3.png)

**Comment by iosifnicolae2** [comment]
PS. I have the following meter: [DTS238-7 WIFI(D3711)](https://www.iecmeter.com/page84?product_id=104)

**Comment by mi-schi** [comment]
The normal Max485 runs with 5V (but not more!), there is a special one Max3485 which can also be powered with 3.3V. Maybe this is the problem. Than there is a USB to RS485 adapter. With this one you can test your meter with your computer and python for example. You can also look into the RS485 communication by connecting an oscilloscope to A and B. It should look like the following picture:
![9AF87988-2F24-4D91-9494-0C375344DF8E](https://user-images.githubusercontent.com/8821732/189751039-0b4b252c-6341-4ea6-82e0-12bf5b36819e.jpeg)

**Comment by iosifnicolae2** [comment]
Ok, got it.

The connection between max485 and esp8266 was made through a voltage
converter (from 5.5v down to 3.3v)?

lun., 12 sept. 2022, 23:21 Michael Schindler ***@***.***> a
scris:

**Comment by mi-schi** [comment]
A good question. I don't know it for 100%. The system runs for some month without any problems, so I never took it out of the subdistributor. Definitely not a voltage divider. Maybe I use a Max3485 but I order it later, so I don't think so. I use the Wemos D1 mini pro for a better wifi connection. This one can be powered via 5V and the Max485 will also be powered with 5V, only the data connection is 3.3V which is okay, see the data sheet:
![image](https://user-images.githubusercontent.com/8821732/190112841-c669a440-4a9e-4d72-b8ce-76ca2a15b4fa.png)
https://datasheets.maximintegrated.com/en/ds/MAX1487-MAX491.pdf
